using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestScriptGeneration
{
    class JsonReading
    {
        string url;

        public List<Rootobject> ReadFile(string file) {
            url = file;
            using (StreamReader r = new StreamReader(url))
            {
                string json = r.ReadToEnd();
                //  List<Rootobject> items = JsonConvert.DeserializeObject<List<Rootobject>>(json);
                List<Rootobject> tc = FromDelimitedJson<Rootobject>(new StringReader(json)).ToList();
                return tc;
            }
        }

        //Customized method to Extract Data from Json Generated by GW
        public IEnumerable<T> FromDelimitedJson<T>(TextReader reader, JsonSerializerSettings settings = null)
        {
            using (var jsonReader = new JsonTextReader(reader) { CloseInput = false, SupportMultipleContent = true })
            {
                var serializer = JsonSerializer.CreateDefault(settings);

                while (jsonReader.Read())
                {
                    if (jsonReader.TokenType == JsonToken.Comment)
                        continue;
                    yield return serializer.Deserialize<T>(jsonReader);
                }
            }
        }
    }
}
